apiVersion: v1
name: TCSKube-do-cluster-template
description: Cluster Template for Digital Ocean
version: 0.1.0
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
