apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  kubernetesVersion: v1.23.8+rke2r1
  rkeConfig:
    controlPlaneConfig:
      cni: {{ .Values.cluster.cni }}
    machinePools:
    - controlPlaneRole: true
      etcRole: true
      workerRole: true
      quantity: {{ .Values.cluster.nodes.count }}
      name: {{ .Values.cluster.name }}-nodes
      machineConfigRef:
        kind: DigitaloceanConfig
        name: {{ .Values.cluster.name }}-nodes
      paused: false
      displayName: {{ .Values.cluster.name }}-nodes
